### ISSUE TITLE
HTTP Connection to VIES not working anymore

### ISSUE THREAD

**Issue by fgehring** [bigpresh/Business-Tax-VAT-Validation#4]
Since today a call to the VIES URL http://ec.europa.eu/taxation_customs/vies/services/checkVatService results in an attempt to redirect from HTTP to HTTPS. Since this does not work on the API level, it results in an error code 257 with the following message:

`Invalid response [302], please contact the author of this module. <HTML><HEAD>  <TITLE>Redirect</TITLE>  </HEAD>  <BODY>  <FONT face="Helvetica">  <big><strong></strong></big><BR>  </FONT>  <blockquote>  <TABLE border=0 cellPadding=1 width="80%">  <TR><TD>  <FONT face="Helvetica">  <big>Redirect (policy_request_redirect)</big>  <BR>  <BR>  </FONT>  </TD></TR>  <TR><TD>  <FONT face="Helvetica">  Click <a href="https:&#x2F;&#x2F;ec.europa.eu&#x2F;taxation_customs&#x2F;vies&#x2F;services&#x2F;checkVatService">here</a> if you are not automatically redirected.  </FONT>  </TD></TR>  <TR><TD>  <FONT face="Helvetica">    </FONT>  </TD></TR>  <TR><TD>  <FONT face="Helvetica" SIZE=2>  <BR>  For assistance, contact your network support team.  </FONT>  </TD></TR>  </TABLE>  </blockquote>  </FONT>  </BODY></HTML>`

To fix this the Base URL needs to be changed from HTTP to HTTPS.

**Comment by fgehring** [comment]
Related PR: https://github.com/bigpresh/Business-Tax-VAT-Validation/pull/5

**Comment by bigpresh** [comment]
Curious - for me, it works fine:

```
$ Business::Tax::VAT::Validation->new->check('CY10xxxxx8W');
["CY-10xxxxx8W"]
```

(removed part of the VAT number I tested with, because it's a real customer's VAT number).

Presumably you have a different env controlling LWP::UserAgent and limiting it from following redirects or something?

Anyway, as SSL is available for it to use, there's no reason not to use it, so I'll get a new release out ASAP with that base_url change.

**Comment by bigpresh** [comment]
1.12 is on its way to CPAN now with this fix.

Thanks!
