### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by kentfredric** [bigpresh/Business-Tax-VAT-Validation#6]
Its unclear if this is GPL, GPL-3, or GPL-1+

Vague: 
https://github.com/bigpresh/Business-Tax-VAT-Validation/blob/5743ce60e7602c298ab1de492fd041b3be86ea90/lib/Business/Tax/VAT/Validation.pm#L19-L22

GPL-1?:
https://github.com/bigpresh/Business-Tax-VAT-Validation/blob/5743ce60e7602c298ab1de492fd041b3be86ea90/lib/Business/Tax/VAT/Validation.pm#L471-L474

GPL-3??:
https://github.com/bigpresh/Business-Tax-VAT-Validation/blob/5743ce60e7602c298ab1de492fd041b3be86ea90/Makefile.PL#L13-L15

Suggesting GPL-1:
https://github.com/bigpresh/Business-Tax-VAT-Validation/blob/5743ce60e7602c298ab1de492fd041b3be86ea90/examples/vat.cgi#L11-L14
https://github.com/bigpresh/Business-Tax-VAT-Validation/blob/5743ce60e7602c298ab1de492fd041b3be86ea90/examples/vat_cli.pl#L11-L14

Obviously, the COPYING file is GPL-3, and it looks like the overwhelming intent was to make it GPL-3 licensed. However, in some places the reference point is slightly ambiguous.

For instance, it's usually stated "Under the GNU Public License version 3", or in other cases "Under the GNU Public License version 3, or at your choice, any newer version", or something like that, to make it less necessary. As-is, I can't tell if the intent is "GPL-3" or "GPL-3+"

**Comment by bigpresh** [comment]
Good point.  Personally I would be happy with any of them, but I agree it needs to be clear which applies.

As I'm not the original author of the code, just the current maintainer, I'm going to attempt to reach out to the original author to find out his intent with regards to the applicable licence, then I'll Make It So.

**Comment by bigpresh** [comment]
I did reach out, but got no response.  I'm going to agree with you that it appears the intent was GPL-3, so I'll go with that.
