### ISSUE TITLE
UK VAT numbers can no longer be validated?

### ISSUE THREAD

**Issue by robrwo** [bigpresh/Business-Tax-VAT-Validation#8]
According to https://ec.europa.eu/taxation_customs/vies/
> As of 01/01/2021, the VoW service to validate UK (GB) VAT numbers ceased to exist while a new service to validate VAT numbers of businesses operating under the Protocol on Ireland and Northern Ireland appeared. These VAT numbers are starting with the “XI” prefix, which may be found in the “Member State / Northern Ireland” drop down under the new entry “XI-Northern Ireland”. Moreover, any quote of “Member State” is replaced by “Member State / Northern Ireland” and any quote of “MS” is replaced by “MS / XI”. All traders seeking to validate UK (GB) VAT numbers may address their request to the UK Tax Administration.

**Comment by bigpresh** [comment]
Thanks for the report Robert.

I'lll try to find a moment to look at this, but I'm short on time at the moment, and no longer use this module at work as I've changed jobs, so I can't make any promises when I'll have time to look at it.

In fact, I'd be perfectly happy to hand the module off to anyone with more interest in dealing with a twisty maze of EU taxation rules than I do, as I have about as much interest in that as I do in being eaten by a grue or being forced to use Windows.

I will thusly go assign co-maint to ADOPTME.

**Comment by bigpresh** [comment]
> I will thusly go assign co-maint to ADOPTME.

... or not, I'm just a co-maint so can't do so.  I have dropped Bernard (BPGN) a mail to let him know that I'd be more than happy to hand over maintainership if someone wants to step up.

(Also, HANDOFF would probably be more appropriate than ADOPTME)

**Comment by robrwo** [comment]
I'm not sure there's anything else you can do for this, perhaps document the issue and add a special handler to convert GB numbers to a different prefix code for Northern Ireland? It's entirely possible a future agreement could re-enable GB validation, so moving the regexes into an attribute that allows them to be modified may be useful.

**Comment by bigpresh** [comment]
Stable release 1.20 is now on its way to CPAN with the work kindly done by @davel in PR #9.
